apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gfw
    name: basemaps
  name: basemaps
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: basemaps
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: basemaps
    spec:
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "4502"
            - name: ENVIRONMENT
              value: prod
            - name: LOCAL_URL
              value: http://basemaps.default.svc.cluster.local:4502
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  key: CT_URL
                  name: mssecrets
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CT_TOKEN
                  name: mssecrets
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  key: CT_REGISTER_MODE
                  name: mssecrets
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  key: API_VERSION
                  name: mssecrets
            - name: EE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: EE_PRIVATE_KEY
                  name: mssecrets
            - name: REDIS_URL
              valueFrom:
                  secretKeyRef:
                    name: dbsecrets
                    key: REDIS_URI_BASEMAP
          image: skydipper/basemaps:master.15
          imagePullPolicy: Always
          name: basemaps
          ports:
            - containerPort: 4502
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: type
          operator: Equal
          value: basemaps
